### PR TITLE
Picker2

### PR DESCRIPTION
**Pull request by Jakidxav**
Creating a pull request to incorporate changes made to migration routines and additional plotting method to display power spectral density. With this we could create a stable branch for people to play with and then move over to a developer branch?

### CODE REVIEW

**Comment by dlilien** [comment]
I've merged this in. In the future, try to avoid `git commit *` or other things that add a lot of files to the repository. The egg-info should not be in the repository, nor should .mat files output by load/save operations in testing (I modified the tests for migration so that they clean up after themselves, so that is a nonissue).

**Comment by dlilien** [comment]
Also I edited where somebody added extrapolation to the constant spacing--I think that was too dangerous because it does not complain when you use entirely incorrect GPS data--but it may break some of you scripts. There is now an option in the function call to turn extrapolation on though.

**Comment by Jakidxav** [comment]
Sorry for all the extra files! I will try to be more careful and commit
files individually as I need them. I made the changes to use constant
spacing because the interpolation script would not load in the precision
GPS data for Herc Dome otherwise. But that could be due to a number of
other things. Thanks for incorporating the changes.

**Comment by dlilien** [comment]
No worries--it is just something to be aware of.

I figured that change to constant spacing was for that reason--my main concern is that the way it was set up you could use entirely incorrect GPS data (e.g. from the wrong season) and it would not give any indication that there was a problem and just fill in the data. When you know that the GPS and radar are close, but the radar extends just a bit too far, as is probably the case for Herc Dome, I think your solution is fine. I gave command-line access to the extrapolate option on the [devel branch](https://github.com/dlilien/ImpDAR/commit/3c2d618f9fd7f09e46d30a47770a26b2928c4238).

**Pull request merged**
