### PR TITLE
ApDAR

### PR DESCRIPTION
**Pull request by benhills**
This is a PR to integrate 'apdar' more thoroughly.

I need to write more unit tests before we merge it but it would be helpful if you can tell codecov to stop ignoring the Apres directory so that I can make sure there is good coverage.

### CODE REVIEW

**Comment by dlilien** [comment]
@benhills I am not sure how to modify the pull request since I cannot push to your fork--but you can get checks to run on codecov by deleting the ApRes folder glob from line 87 of .github/workflows/python-package.yml.

**Comment by benhills** [comment]
Thanks. I should have been able to figure that out on my own, but thanks for the pointer. 
I will update the testing scripts for more coverage.

**Comment by dlilien** [comment]
OK, just let me know when you are happy with test coverage and we can merge. It looks to me like the one failing check is some weird problem with the image, not with us, so I am fine ignoring that.

**Comment by benhills** [comment]
I still need to finish the docs but I think this PR is probably ready whenever. I can try to deal with that last pest in codecov as well.

**Pull request merged**
