### PR TITLE
ApRES; Impulse load files; Herc Dome GPS

### PR DESCRIPTION
**Pull request by benhills**
Cherry picking commits from the quadpol repository for some of the updated ApRES functionality.
Typo in load_apres() where the datetime backward-compatibility addition was +377 days instead of +366.
**Note: This could cause some issues for folks if they process one acquisition before and one after this PR and then compare for vertical velocities.

Some small changes to load files including a new load type for TEK data (from Twit Conway and Ginny Catania).

Include some functionality for interpolation through spotty GPS data at Hercules Dome.

### CODE REVIEW

**Comment by benhills** [comment]
I will deal with these issues above, sorry about that.

**Comment by benhills** [comment]
I will deal with the python issues that are showing up, sorry about that.

**Comment by benhills** [comment]
Python 3.8 and 3.9 seem to have an issue with the scipy minimize function as it is written. I can't get it to fail on my local tests though, even with 3.9.

**Comment by dlilien** [comment]
I am not sure if I can write directly to this, but I think this is a scipy bug. Try adding ',<1.8' in the scipy line of requirements.txt and see if that fixes it.

**Comment by benhills** [comment]
That seems to have helped. There is still one failing but it doesn't really give any info on why this particular check failed.

I am also seeing that load_tek does not get covered by any tests, so let me write a test for that before this gets merged.

**Comment by benhills** [comment]
The remaining fails are all to do with the windows build and seem to be a broader python issue.
I am not sure what the etiquette is here. This PR does not need to get merged with any urgency, I just wanted to push a few things through before I got so far behind again.

**Pull request merged**
