### PR TITLE
Auto Picker 

### PR DESCRIPTION
**Pull request by benhills**
We probably want to deal with #18 before this one, but I am opening it now. Let me know if that is not proper etiquette, I am still getting used to this stuff. 

This is work that I did on the gui this summer to implement an autopicker. The current state is not finished (hence remaining on devel branch), but there is some functionality that could be useful to someone possibly. Also, this is not a priority of mine right now, so I figured I would submit a pull request before I forget about it. The idea is to select one point on the radar image and it will automatically pick that layer across the extent of the image. As of now, the picking algorithm is the same as the standard picker, which goes trace-by-trace to isolate the wavelet that is nearest to that of the previous trace.

I haven't thoroughly reviewed the changes, but at least Travis is happy. Eventually someone should probably clean up this work as well as the rest of the GUI code. Definitely feel free to put this on hold if you think we should put more work into the gui before moving this into devel.

### CODE REVIEW

**Comment by dlilien** [comment]
I'm going to hold off on this for a bit. A number of people are using the devel version since when new loaders are needed I put them on there to avoid problems with master. Let's plan on merging devel into master and having to test that in December. After that merge, we should revisit this.

**Comment by benhills** [comment]
Yeah that is no problem. Maybe that will give me a chance to clean things up.

Also, it looks like I need to look into this 'coveralls' thing. That is new to me.

**Comment by dlilien** [comment]
Yeah, don't worry too much about coveralls. It will say that checks have failed if test coverage decreases, but I think we should prioritize getting features in, and if you can write useful tests then that is great too.

**Comment by benhills** [comment]
I added some commits here that address #20. Still no rush on pushing this forward.

**Comment by dlilien** [comment]
No tests run due to problems with travis.com billing. Going to put this all in, then get tests running.

**Pull request merged**
