### PR TITLE
bug fixes in load_bsi.py file

### PR DESCRIPTION
**Pull request by EmmaErwin93**
edited the load_bsi.py file to fix bug that was reading in the sampling rate incorrectly and throwing off the time vector

### CODE REVIEW

**Comment by dlilien** [comment]
@EmmaErwin93 I think I incorporated these changes in #47, but it would be great if you can confirm that this new version works as expected--if so, we can close this.

**Comment by EmmaErwin93** [comment]
@dlilien I have tested with some BSI files and this issue with the sampling rate is fixed now - thanks!

 but, there is an issue now with the way latitude coordinates are being read in. It looks like there is an issue with *-1 by the **longitude** coordinates. I haven't been able to figure out why, unless there is an issue with an absolute value somewhere. I have attached an image for reference (blue is correctly georeferenced ; orange is using version #47)
Jarvistest_latlong

**Comment by dlilien** [comment]
@EmmaErwin93 can you clarify which coordinate is incorrect? Latitudes >90 do not exist, so there is also some kind of issue with the coordinates being exchanged in that plot. I guess it is the longitude that is being read incorrectly for you?

Second, is this coming from 040716-10.h5? I just checked, and I get that correctly georeferenced (or it plots on Jarvis). If this is a different file, can you put it somewhere I can see it (or check what string relates to Longitude in the gps cluster data on line 0, location 0?

**Comment by EmmaErwin93** [comment]
@dlilien wow sorry my brain was somewhere else! Just updated the prior comment -- the *Longitude* coordinates are where I am seeing a difference between files I loaded previously and using this new load_bsi file (longitude coordinates are saving  in the .mat file as positive instead of negative, throwing it into the Eastern hemisphere instead of the Western)? And yes, sorry - this file is from 040716-10.h5 and should plot on the centerline of Jarvis Glacier. 

Perhaps the issues is just on my end with just pulling in the new load_bsi file instead of pulling a full impdar update?

**Comment by dlilien** [comment]
It is locaed correctly for that data on my machine with the most recent ImpDAR, so unless you find issues on other machines or after a full update, I think this somehow is coming from something specific to your setup.

**Comment by EmmaErwin93** [comment]
@dlilien i just pulled the full update and still get the same issue -- but its very possible this could just be something with various adjustments i've made to the machine i'm on. I'll close this thread and reach back out if I hear from others who have experienced similar georeferencing issues, after making sure they've pulled this latest full update.

**Pull request closed without merging**
